# Generated by Django 5.1.6 on 2025-03-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
